mwi = '18037_0.mwi'


pyautogui.hotkey('alt')
pyautogui.hotkey('enter')
pyautogui.hotkey('down')
pyautogui.hotkey('enter')
time.sleep(1)
pyautogui.typewrite(mwi)
pyautogui.hotkey('enter')
time.sleep(1)
# the channel mapping window
if pyautogui.locateOnScreen('wrong.png') == True:
    break
pyautogui.hotkey('tab')
pyautogui.hotkey('space')
pyautogui.typewrite('ECG')
pyautogui.hotkey('enter')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('space')
pyautogui.typewrite('resp')
pyautogui.hotkey('enter')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('space')
pyautogui.typewrite('zo')
pyautogui.hotkey('enter')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('space')
pyautogui.typewrite('dz')
pyautogui.hotkey('enter')
pyautogui.hotkey('shift', 'tab')
pyautogui.hotkey('shift', 'tab')
pyautogui.hotkey('shift', 'tab')
pyautogui.hotkey('shift', 'tab')
pyautogui.hotkey('shift', 'tab')
pyautogui.hotkey('enter')
## going back to the main window
time.sleep(1)
pyautogui.hotkey('alt')
pyautogui.hotkey('enter')
pyautogui.hotkey('down')
pyautogui.hotkey('down')
pyautogui.hotkey('down')
pyautogui.hotkey('down')
pyautogui.hotkey('enter')
time.sleep(1)
pyautogui.hotkey('enter')
time.sleep(1)
pyautogui.hotkey('enter')
pyautogui.hotkey('enter')
time.sleep(1)
